services:
  spark-notebook:
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./scala_notebooks:/workspace
    environment:
      - SPARK_MASTER=local[*]
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --ServerApp.allow_origin='*'